Added tone()
adafruit/Adafruit_CircuitPython_SimpleIO pull request #12
Opened 2017-07-24 21:17 UTC by brentru

Issue #2 
added tone() to generate square wave w/50% duty cycle and variable frequency

2017-07-25 16:43 UTC, tannewt requested changes
Thanks for picking these up!

2017-07-25 16:43 UTC, tannewt commented on simpleio.py
> +    pwm.deinit(pin)
Have you tried this? I don't think the pwm object will persist across the `tone` and `noTone` calls. It also doesn't take a pin in.

Adding support for the analog out pin would also be nice. PWM doesn't work with it but AudioOut does.

2017-07-25 16:43 UTC, tannewt commented on simpleio.py
> +    :param bitOrder: order to shift bits (either LSBFIRST or MSBFIRST)
I'd make this a bool instead of a string and give it a default. So something like `msb_first=True`.

2017-07-25 16:43 UTC, tannewt commented on simpleio.py
> +    :param value: RETURNS the value read
Returns are documented like:

```
:return: the device's usage page
:rtype: int
```

(from [here](https://github.com/adafruit/circuitpython/blob/master/shared-bindings/usb_hid/Device.c#L72))

2017-07-25 16:43 UTC, tannewt commented on simpleio.py
> +        dataPin.switch_to_output()
Lets use the property in examples where we don't provide arguments to `switch_to_output`.

So it should be `clock.direction = digitalio.Direction.OUTPUT`

2017-08-01 17:28 UTC, tannewt commented
Please rebase this now that the shift code is in.

2017-08-09 14:48 UTC, brentru commented
Rebased.

2017-08-09 17:01 UTC, tannewt commented
What did you rebase onto? It looks likes the tone branch is still based on a commit from April. The `Files changed` tab shows a ton of changes unrelated to `tone`.

2017-08-09 18:53 UTC, tannewt commented on simpleio.py
> +            time.sleep(1)
`time.sleep(duration)`

2017-08-09 18:54 UTC, tannewt approved these changes
Thank you so much for doing this!

2017-08-09 18:57 UTC, merged