https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO/issues/10
adafruit/Adafruit_CircuitPython_SimpleIO pull request #30
Opened 2018-05-15 19:32 UTC by apatt

I was able to test that the parameter passing works as expected and that there are not python errors, but I don't know to confirm the underlying functions (switch_to_input and switch_to_output) functions work as expected.

2018-05-17 17:04 UTC, tannewt requested changes
THanks for picking this up. A couple comments to simplify things.

2018-05-17 17:04 UTC, tannewt commented on simpleio.py
> +    def __init__(self, pin, value=None, drive_mode=None):
Simpler to do `def __init__(self, pin, **kwargs):`

2018-05-17 17:04 UTC, tannewt commented on simpleio.py
> +            see digitalio.DigitalInOut.switch_to_output for more details
Please copy the docs here. Directing elsewhere doesn't simplify the docs.

2018-05-18 01:54 UTC, apatt commented
ok, fixed all of your comments.  again, tested to make sure python doesn't fail.

2018-05-18 17:08 UTC, tannewt approved these changes

2018-05-18 17:08 UTC, tannewt commented
Thanks @apatt !

2018-05-18 17:08 UTC, merged